bot manager changes, additional bot hooks
XRFoundation/XREngine-Bot pull request #30
Opened 2023-04-11 16:20 UTC by SYBIOTE

bot manager now accepts ID to add and delete bot instead of name, more compatible with the feathers framework that way 
added bot hooks to get  position, transfrom, rotation and check if the engine is in bot state

2023-04-11 17:40 UTC, SYBIOTE commented
@cla-bot check

2023-04-11 20:40 UTC, HexaField requested changes

2023-04-11 20:40 UTC, HexaField commented on tsconfig.json
> +, "../../../server-core/src/bot/bot/bot-helper.ts"  ]
Please revert

2023-04-11 21:03 UTC, SYBIOTE commented on tsconfig.json
> +, "../../../server-core/src/bot/bot/bot-helper.ts"  ]
sure

2023-04-16 14:11 UTC, mrhegemon approved these changes

2023-04-16 14:11 UTC, merged